export const REACT_APP_EMAILJS_SERVICE = process.env.REACT_APP_EMAILJS_SERVICE;
export const REACT_APP_EMAILJS_TEMPLATE = process.env.REACT_APP_EMAILJS_TEMPLATE;
export const REACT_APP_EMAILJS_PUBLICK_KEY = process.env.REACT_APP_EMAILJS_PUBLICK_KEY;
